# -*- coding: utf-8 -*-
"""Patterns-28 May

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16U0OPSC_N-UNAQ27WpT0cjD-6bVaTo2r
"""

for i in range(1,6):
  for j in range(1,1+i):
    print(j,end=' ')
  print( )

for i in range(1,6):
  for j in range(1,i+1):
    print('-',end=' ')
  for k in range(1,5-i+1):
    print('*',end=' ')
  print( )

for i in range(1,6):
  for j in range(1,5-i+1):
    print('-',end=' ')
  for k in range(i):
    print('*',end=' ')
  print( )

for i in range(1, 6):
    for k in range(1, i + 1):
        print(k, end=' ')
    X = 65
    for j in range(1, 5 - i+1):
        print(chr(X), end=' ')
        X += 1
    print()

for i in range(1,6):
  for k in range(1,i+1):
    if(k==1 or i==5 or i==k):
      print('*',end=' ')
    else:
      print('-',end=' ')
  print( )

for i in range(5,0,-1):
  for k in range(1,i+1):
    if(k==1 or i==5 or i==k):
      print('*',end=' ')
    else:
      print('-',end=' ')
  print( )

for i in range(1, 6):
    for j in range(1, i):
        print('-', end=' ')
    for k in range(1, 6 - i + 1):
        if k == 1 or k == 5 - i + 1 or i == 1:
            print('*', end=' ')
        else:
            print(' ', end=' ')
    print()